name: data_table_alamat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flag: ^6.0.0
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  flutter_svg: ^1.0.1
  http: ^0.13.6
  line_icons: ^2.0.1
  parse_server_sdk_flutter: ^4.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
